### ISSUE TITLE
Request for more supported indicators

### ISSUE THREAD

**Issue by shobrook** [themichaelusa/realtime_talib#10]
I'd find it really useful if the following were supported: TRIX (Triple Exponential Moving Average), OBV (On-Balance Volume), ATR (Average True Range), and ROCR (Rate of Change Ratio).

**Comment by themichaelusa** [comment]
Added all the above indicators. TRIX is actually named TEMA in TA-Lib. Wrote test cases for each under test.py. Testing now.

**Comment by themichaelusa** [comment]
Correction: TRIX is actually the 1-day Rate-Of-Change (ROC) of a Triple Smooth EMA.

**Comment by themichaelusa** [comment]
Also, all 4 indicators work and produce valid historical and realtime results.
